# Generated by Django 2.2.16 on 2022-11-10 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название группы')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug для url')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'default_related_name': 'group',
                'verbose_name': 'группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст (обязательное поле)', verbose_name='Текстовое поле')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(help_text='Укажите автора поста (обязательное поле)', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('group', models.ForeignKey(blank=True, help_text='Выберите группу из списка (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group', verbose_name='Группа')),
                ('image', models.ImageField(blank=True, help_text='Выберите картинку (опционально)', null=True, upload_to='posts/', verbose_name='Изображение')),
            ],
            options={
                'default_related_name': 'post',
                'ordering': ['-created'],
                'verbose_name': 'пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст (обязательное поле)', verbose_name='Текстовое поле')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(help_text='Укажите автора комментария (обязательное поле)', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(help_text='Выберите пост из списка (обязательное поле)', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post', verbose_name='Комментарий к посту')),
                ('image', models.ImageField(blank=True, help_text='Выберите файл (опционально)', null=True, upload_to='photos/comments/%Y/%m/%d/', verbose_name='Изображение')),
                ('child', models.ForeignKey(blank=True, help_text='Выберите комментарий из списка (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='posts.Comment', verbose_name='Комментарий в треде')),
                ('is_child', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created'],
                'default_related_name': 'commentary',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, help_text='Укажите авторов для подписки', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('user', models.ForeignKey(help_text='Укажите пользователя ленты', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_follow'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(help_text='Укажите пользователя лент', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(help_text='Укажите пользователя ленты', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Без заголовка', help_text='Введите Название поста (обязательное поле)', max_length=255, verbose_name='Название поста'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите картинку (опционально)', null=True, upload_to='photos/posts/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
