# Generated by Django 2.2.6 on 2022-09-05 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220905_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='child',
            field=models.ForeignKey(blank=True, help_text='Выберите комментарий из списка (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Commentary', verbose_name='Комментарий в треде'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='author',
            field=models.ForeignKey(help_text='Укажите автора комментария (обязательное поле)', on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='commentary',
            field=models.ForeignKey(help_text='Выберите пост из списка (обязательное поле)', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.Post', verbose_name='Комментарий к посту'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите файл (опционально)', null=True, upload_to='photos/comments/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='text',
            field=models.TextField(help_text='Введите текст комментария (обязательное поле)', verbose_name='Текст сообщения'),
        ),
    ]
