# Generated by Django 2.2.6 on 2022-09-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220905_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
