# Generated by Django 2.2.16 on 2022-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_commentary_is_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите картинку (опционально)', null=True, upload_to='photos/posts/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
