# Generated by Django 2.2.16 on 2022-09-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220911_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='child',
            field=models.ForeignKey(blank=True, help_text='Выберите комментарий из списка (опционально)', null=True, on_delete=models.SET('Комментарий удален'), related_name='comments', to='posts.Commentary', verbose_name='Комментарий в треде'),
        ),
    ]
