# Generated by Django 2.2.16 on 2022-09-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220915_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='child',
            field=models.ForeignKey(blank=True, help_text='Выберите комментарий из списка (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Commentary', verbose_name='Комментарий в треде'),
        ),
    ]
