# Generated by Django 2.2.16 on 2022-09-16 12:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0016_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentary',
            new_name='Comment',
        ),
    ]
