# Generated by Django 2.2.16 on 2022-09-16 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20220916_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Укажите автора комментария (обязательное поле)', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='child',
            field=models.ForeignKey(blank=True, help_text='Выберите комментарий из списка (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='posts.Comment', verbose_name='Комментарий в треде'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(help_text='Выберите пост из списка (обязательное поле)', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post', verbose_name='Комментарий к посту'),
        ),
    ]
