# Generated by Django 2.2.16 on 2022-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20220916_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Введите текст (обязательное поле)', verbose_name='Текстовое поле'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст (обязательное поле)', verbose_name='Текстовое поле'),
        ),
    ]
