# Generated by Django 2.2.16 on 2022-10-05 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_squashed_0029_auto_20220924_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BooleanField(help_text='Укажите лайк или дизлайк', verbose_name='Лайки')),
                ('post', models.ForeignKey(help_text='Пост, которому ставят лайк/дизлайк', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.Post', verbose_name='Комментарий к посту')),
                ('user', models.ForeignKey(help_text='Пользователь, который ставит лайк/дизлайк', on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'post', 'rating'), name='unique_rating'),
        ),
    ]
