# Generated by Django 2.2.16 on 2022-10-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20221005_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(help_text='Укажите лайк или дизлайк', verbose_name='Лайки'),
        ),
    ]
